# Generated by Django 4.2.20 on 2025-08-05 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LungData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GENDER', models.CharField(max_length=100)),
                ('AGE', models.IntegerField()),
                ('SMOKING', models.FloatField()),
                ('YELLOW_FINGERS', models.FloatField(max_length=100)),
                ('ANXIETY', models.FloatField(max_length=100)),
                ('PEER_PRESSURE', models.FloatField()),
                ('CHRONIC_DISEASE', models.FloatField()),
                ('FATIGUE', models.FloatField()),
                ('ALLERGY', models.FloatField(max_length=100)),
                ('WHEEZING', models.FloatField(max_length=100)),
                ('ALCOHOL_CONSUMING', models.FloatField(max_length=100)),
                ('COUGHING', models.FloatField(max_length=100)),
                ('SHORTNESS_OF_BREATH', models.FloatField(max_length=100)),
                ('SWALLOWING_DIFFICULTY', models.FloatField(max_length=100)),
                ('CHEST_PAIN', models.FloatField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
