# Generated by Django 4.1.2 on 2026-02-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Heart_rate_BPM', models.IntegerField()),
                ('Heart_rate_variability', models.FloatField()),
                ('Respiratory_rate', models.IntegerField()),
                ('Mental_Fatigue_level', models.FloatField()),
                ('Reaction_time_delay', models.FloatField()),
                ('Adrenaline', models.FloatField()),
                ('Cortisol_level', models.FloatField()),
                ('Stress_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LungData',
        ),
    ]
